# Generated by Django 5.0.14 on 2025-11-01 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0002_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giveaways', to='giveaway.station'),
        ),
    ]
