# Generated by Django 5.0.14 on 2025-11-01 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0003_station_station_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_fk',
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giveaways', to='giveaway.station'),
        ),
    ]
