# Generated by Django 5.0.14 on 2025-11-01 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0004_remove_station_station_fk_alter_giveaway_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prize',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='giveaway',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='giveaway.giveaway'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='winner',
            name='prize',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='giveaway.prize'),
        ),
    ]
